
name: Learning Github Actions
run-name: Learning Actions
on: [push]
jobs:
    hello-actions:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Define envs
              run: echo "USER=${{ github.actor }}" >> $GITHUB_ENV
            - name: Run script
              run: python hello-github-actions.py
